# Generated by Django 5.0.6 on 2025-07-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imdb', models.FloatField()),
                ('genre', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('time', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imdb', models.FloatField()),
                ('genre', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('season', models.IntegerField()),
                ('chapter', models.IntegerField()),
            ],
        ),
    ]
