# Generated by Django 5.2.1 on 2025-08-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_genre_remove_movie_country_remove_serie_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="movie",
        ),
        migrations.RemoveField(
            model_name="country",
            name="serie",
        ),
        migrations.AddField(
            model_name="movie",
            name="country",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.country",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serie",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.country",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.DateField(),
        ),
    ]
