# Generated by Django 5.2.1 on 2025-08-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_country_movie_remove_country_serie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                default=1, upload_to="../build/static/media/images"
            ),
            preserve_default=False,
        ),
    ]
