# Generated by Django 5.2.1 on 2025-08-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(upload_to="build/static/media/images/"),
        ),
    ]
