# Generated by Django 5.2.1 on 2025-08-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(upload_to="api/media/images/"),
        ),
    ]
