# Generated by Django 5.2.1 on 2025-08-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_movie_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="time",
            new_name="hour",
        ),
        migrations.AddField(
            model_name="movie",
            name="minute",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serie",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="api/images/"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="api/images/"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="serie",
            name="year",
            field=models.IntegerField(),
        ),
    ]
