# Generated by Django 5.2.1 on 2025-08-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_rename_rating_movierating_serierating"),
    ]

    operations = [
        migrations.AddField(
            model_name="serierating",
            name="isDislike",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serierating",
            name="isFavorite",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serierating",
            name="isLike",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serierating",
            name="stars",
            field=models.FloatField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="serierating",
            name="rating",
            field=models.FloatField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
            ),
        ),
    ]
