# Generated by Django 5.2.1 on 2025-08-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_movierating_isdislike_movierating_isfavorite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movierating",
            name="rating",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="movierating",
            name="stars",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="serierating",
            name="rating",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="serierating",
            name="stars",
            field=models.FloatField(),
        ),
    ]
