# Generated by Django 5.2.1 on 2025-08-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_movierating_rating_alter_movierating_stars_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movierating",
            name="rating",
            field=models.FloatField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
            ),
        ),
    ]
