# Generated by Django 5.2.1 on 2025-08-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_alter_movierating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movierating",
            name="rating",
            field=models.FloatField(),
        ),
    ]
