# Generated by Django 5.2.1 on 2025-08-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_alter_movierating_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="movierating",
            name="isBookmark",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serierating",
            name="isBookmark",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movierating",
            name="stars",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="serierating",
            name="stars",
            field=models.IntegerField(),
        ),
    ]
