# Generated by Django 5.2.1 on 2025-08-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_movierating_isbookmark_serierating_isbookmark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movierating",
            name="isWatched",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="serierating",
            name="isWatched",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
