# Generated by Django 5.0.6 on 2025-01-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15)),
                ('user_email', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=20)),
            ],
        ),
    ]
