# Generated by Django 5.2.1 on 2025-07-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
