# Generated by Django 5.2.1 on 2025-07-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
